language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - hhvm

sudo: false

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

before_script:
  - composer self-update
  - composer update --no-interaction $PREFER_LOWEST

script:
  - phpunit --coverage-clover tests/clover.xml

after_script:
  - php vendor/bin/coveralls -v
