language: php

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5

sudo: false

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

before_script:
  - composer self-update
  - composer update --no-interaction $PREFER_LOWEST

script:
  - vendor/bin/phpunit

after_script:
  - php vendor/bin/coveralls --verbose
